addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"            % "1.0.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("org.tpolecat"     % "tut-plugin"           % "0.6.9")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "2.3")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"              % "2.0.0-M2")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"           % "3.1.0")
